### ISSUE TITLE
[API] Aggregate more data to hydric systems

### ISSUE THREAD

**Issue by ubiratansoares** [rafaell-lycan/sabesp-mananciais-api#32]
Dados extras que podem ser adicionados em relação as represas!

http://arte.folha.uol.com.br/cotidiano/2015/04/02/reservatorios/datas/reservatorios.json

Essas informações poderiam ser agregadas no retorno da própria chamada /vX/{date} ou como uma chamada separada ...

Testei a chamada em outras URLs (2015/06/26 por ex) sem sucesso ... Penso que essa informação é mais estática, embora o número de pessoas atendidas por um ou outro complexo hídrico possa variar de acordo com as políticas de distribuição de água da Sabesp

**Comment by wbruno** [comment]
Sem ter histórico disso fica ruim, pq ai não podemos afirmar que a 2 anos atrás a população atendida era a mesma de hoje, ou de 2015. 
Vou encontrar outra fonte para esse tipo de informação.
