### ISSUE TITLE
[Crawler] Leverage alternative data source to feed info

### ISSUE THREAD

**Issue by ubiratansoares** [rafaell-lycan/sabesp-mananciais-api#33]
Olhando no site da folha, encontrei esse link

http://arte.folha.uol.com.br/databases/cotidiano/2014/mananciais/mananciais.csv

Apesar do "2014" tendencioso na URL, ele vai retornar um CSV com todas as informaçãos de cada represa até a data atual :)

Penso que pode ser uma boa alternativa (ou substituto!) do crawler direto do site da Sabesp!

O que acham?

[]s

**Comment by wbruno** [comment]
Muito bom cara! curti! hehe
Muito mais fácil de fazer parser.
